config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :products do
      resources :stocks
    end
    resources :categories
  end

  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'home#index'

  authenticated :admin_user do
    root to: 'admin#user', as: :admin_root
  end

  get 'admin' => 'admin#index'
end

app/models/product.rb
# t.string "name"
# t.text "description"
# t.integer "price"
# t.integer "category_id", null: false
# t.boolean "active"
# t.datetime "created_at", null: false
# t.datetime "updated_at", null: false
# t.index ["category_id"], name: "index_products_on_category_id"

class Product < ApplicationRecord
  belongs_to :category
  has_many :stocks

  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
    attachable.variant :medium, resize_to_limit: [250, 250]
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  PRODUCTS_PER_PAGE = 30
  before_action :set_admin_product, only: %i[show edit update destroy]

  # GET /admin/products
  def index
    @admin_products = Product.includes([:category, { images_attachments: [:blob] }])
                             .order(created_at: :desc)
                             .page(params[:page])
                             .per(PRODUCTS_PER_PAGE)
    @admin_product = Product.new
    @categories = Category.order(:name)
  end

  # GET /admin/products/1 or /admin/products/1.json
  def show; end

  # GET /admin/products/new
  def new
    @admin_product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /admin/products or /admin/products.json
  def create
    @admin_product = Product.new(admin_product_params)

    if @admin_product.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend('products', partial: 'admin/products/product',
                                                                locals: { product: @admin_product })
        end
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
      end
    else
      render :index
    end
  end

  # PATCH/PUT /admin/products/1 or /admin/products/1.json
  def update
    respond_to do |_format|
      if @admin_product.update(admin_product_params.reject { |item| item['images'] })
        admin_product_params['images']&.each { |image| @admin_product.images.attach(image) }
        redirect_to admin_products_path, notice: 'Product was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  # DELETE /admin/products/1 or /admin/products/1.json
  def destroy
    @admin_product.destroy!

    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_admin_product
    @admin_product = Product.where(id: params[:id]).includes([{ images_attachments: [:blob] }]).first
  end

  # Only allow a list of trusted parameters through.
  def admin_product_params
    params.require(:product).permit(:name, :description, :price, :category_id, :active, images: [])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, admin_product], class: "contents") do |form| %>
  <% if admin_product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
        <% admin_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <% if admin_product.images.any? %>
      <% admin_product.images.each do |image| %>
        <%= image_tag image, class: "w-20 h-20 object-cover rounded-md" %>
        <% end %>
    <% end %>
    <%= form.label :images %> 
    <%= form.file_field :images, multiple: true, class: "block shadow rounded-md border border-gray-200 outline-none py-2 mt-2 px-3 w-full" %> 
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.number_field :price, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.collection_select :category_id, @categories, :id, :name, prompt: "Select a category", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :active %>
    <%= form.check_box :active, class: "block mt-2 h-5 w-5" %>
  </div>

  <% if admin_product.id %>
    <div class="my-5">
      <%= link_to "Product Stock", admin_product_stocks_path(admin_product), class: "underline" %>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<tr class="bg-gray-50 border-b">
  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800 underline">
    <%= product.images.present? ? image_tag(product.images.first.variant(:thumb)) : image_tag("https://via.placeholder.com/50") %>
  </td>

  <td class="px-6 py-4 whitepsace-nowrap text-sm font-medium text-gray-800 underline">
    <%= link_to product.name, edit_admin_product_path(product) %>
  </td>

  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800 underline">
    <%= product.description %>
  </td>

  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800 underline">
    $ <%= product.price %>
  </td>

  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800">
    <%= product.category.name%>
  </td>

  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800">
  <%= product.active %>
  </td>

  </tr>

app/views/admin/products/create.turbo_stream.erb
<%#= turbo_stream.prepend "products", partial: "admin/products/product", locals: { product: @admin_product } %>

app/views/admin/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>

  <%= render "form", admin_product: @admin_product %>

  <%= link_to "Show this product", [:admin, @admin_product], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/products/index.html.erb
<div class="container mx-auto" data-controller="products" data-action="click->products#clickOutside">

  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Products" %>

  <!-- Button to trigger modal -->
  <div class="flex justify-between items-center">
    <button id="new-product-btn" class="bg-blue-500 text-white px-4 py-2 rounded" data-action="click->products#openModal">
      Add New Product
    </button>
  </div>

  <div class="flex flex-col w-full">
    <div class="overlow-x-auto sm:mx-0.5 lg:mx-0.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overlow-x-auto">
          <table class="min-w-full overflow-x-scroll">
            <thead class="bg-white border-b">
              <tr>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Name
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Description 
                </th>
              </tr>
            </thead>
            <tbody is="turbo-frame" id="products">
              <%= render @admin_products %>
            </tbody>
          </table>
          <div class="mt-8">
          <%= paginate @admin_products %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div id="product-modal" class="hidden fixed z-50 inset-0 bg-gray-800 bg-opacity-50 flex justify-center items-center">
    <div class="bg-white p-6 rounded-lg w-1/3">
      <h2 class="text-2xl font-semibold mb-4">Add New Product</h2>
      <div data-action="turbo:submit-end->products#hideOnSubmit">
        <%= render 'form', admin_product: @admin_product %>
      </div>
      <button class="mt-4 bg-red-500 text-white px-4 py-2 rounded" data-action="click->products#closeModal">Close</button>
    </div>
  </div>

</div>

app/views/admin/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", admin_product: @admin_product %>

  <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/products/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @admin_product %>

    <%= link_to "Edit this product", edit_admin_product_path(@admin_product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this product", admin_product_path(@admin_product), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>